name: issuesuite-action
description: Install and run IssueSuite sync
inputs:
  config:
    description: Config file path
    required: false
    default: issue_suite.config.yaml
  dry-run:
    description: Whether to perform a dry-run before update
    required: false
    default: "true"
runs:
  using: composite
  steps:
    - name: Install IssueSuite
      run: python -m pip install --upgrade pip && pip install .
      shell: bash
    - name: Dry-run sync
      if: inputs.dry-run == 'true'
      run: issuesuite sync --dry-run --update --config ${{ inputs.config }} || true
      shell: bash
    - name: Apply sync
      run: issuesuite sync --update --config ${{ inputs.config }} || true
      shell: bash
