repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-psutil>=5.9.5.20240516
          - types-PyYAML>=6.0.12.20240917
          - types-requests>=2.32.0.20240914
        files: ^src/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # General sanity checks
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key
        exclude: ^(tests/test_github_app_auth\.py|tests/test_github_app_integration\.py|tests/test_errors\.py|src/issuesuite/errors\.py)$
      - id: debug-statements
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt
  - repo: local
    hooks:
      - id: cleanup-macos-cruft
        name: Cleanup macOS metadata
        entry: ./cleanup-macos-cruft.sh --include-git
        language: system
        pass_filenames: false
