name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev,all]
      - name: Lint (ruff)
        run: |
          python -m ruff check
      - name: Typecheck (mypy)
        run: |
          python -m mypy src
      - name: Test (pytest)
        env:
          ISSUES_SUITE_MOCK: "1"
        run: |
          python -m pytest -q
      - name: Run quality gates
        if: matrix.python-version == '3.11'
        run: python scripts/quality_gates.py
