name: Dependency Synchronization

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "docs/starlight/package.json"
      - "docs/starlight/package-lock.json"
      - "scripts/refresh-deps.sh"
      - ".github/workflows/dependencies.yml"
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      - "docs/starlight/package.json"
      - "docs/starlight/package-lock.json"
      - "scripts/refresh-deps.sh"

permissions:
  contents: read

jobs:
  check-lockfiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.11"

      - name: Install uv
        run: pip install --user uv

      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6
        with:
          node-version: "20"

      - name: Validate lockfiles are synchronized
        run: ./scripts/refresh-deps.sh --check

      - name: Show remediation instructions on failure
        if: failure()
        run: |
          echo "::error::Lockfiles are out of sync with manifests"
          echo ""
          echo "To fix this issue:"
          echo "1. Run: ./scripts/refresh-deps.sh"
          echo "2. Commit the updated lockfiles: git add uv.lock docs/starlight/package-lock.json"
          echo "3. Push your changes"
          echo ""
          echo "This ensures reproducible builds across all environments."
