name: Lint & Types

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -e '.[dev,all]'
      - name: Ruff lint
        run: ruff check .
      - name: Ruff format (diff only)
        run: ruff format --check .
      - name: Type check
        run: mypy src/issuesuite
