name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      test_pypi:
        description: 'Publish to Test PyPI instead of PyPI'
        required: false
        default: false
        type: boolean

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: read
      attestations: write
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pip-audit cyclonedx-bom

      - name: Install project with dev dependencies
        run: pip install -e .[dev,all]

      - name: Run quality gates (preflight checks)
        run: python scripts/quality_gates.py

      - name: Build package
        run: python -m build

      - name: Generate SBOM for distribution artifacts
        uses: anchore/sbom-action@v0
        with:
          path: dist
          artifact-name: issuesuite-sbom

      - name: Check package
        run: twine check dist/*

      - name: Dependency audit (pip-audit)
        run: pip-audit --strict --progress-spinner off

      - name: Generate build provenance attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "dist/*"

      - name: Publish package distributions to Test PyPI
        if: github.event.inputs.test_pypi == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true

      - name: Publish package distributions to PyPI
        if: github.event.inputs.test_pypi != 'true'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
