name: Release
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: read
  id-token: write
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"
      - name: Build
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*
      - name: Generate Homebrew formula
        run: python scripts/homebrew_formula.py --dist-dir dist --output packaging/homebrew/Formula/issuesuite.rb
      - name: Upload Homebrew formula
        uses: actions/upload-artifact@v4
        with:
          name: homebrew-formula
          path: packaging/homebrew/Formula/issuesuite.rb
      - name: Publish (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
