name: Release
on:
  push:
    tags:
      - v*.*.*
permissions:
  contents: read
  id-token: write
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6
        with:
          python-version: "3.13"
      - name: Build
        run: |
          python -m pip install --upgrade pip build twine
          python -m build
          twine check dist/*
      - name: Generate Homebrew formula
        run: python scripts/homebrew_formula.py --dist-dir dist --output packaging/homebrew/Formula/issuesuite.rb
      - name: Upload Homebrew formula
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: homebrew-formula
          path: packaging/homebrew/Formula/issuesuite.rb
      - name: Publish (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
